---
name: Provision-Test

'on':
  push:

jobs:
  build:
    if: ${{ !(contains(github.ref, 'tags/')) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: build --snapshot

  release:
    if: ${{ contains(github.ref, 'tags/') }}
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: release
          distribution: goreleaser
          version: '~> v2'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
